include: package:lint/analysis_options.yaml

analyzer:
  exclude: 
    - build/**
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"
  enable-experiment:
    - non-nullable

linter:
  rules:
    # Rationale: in our app, the codes are for reading on mobile phones, adding
    # `this` makes it easier for readers to understand which variables class
    # members and which ones are not.
    unnecessary_this: false
    # Same as above, allow writing local variable types to improve readability
    # without IDE.
    omit_local_variable_types: false
    # We sometimes have print statements just for demo purposes.
    avoid_print: false
    use_string_buffers: false
    avoid_redundant_argument_values: false
    prefer_const_constructors: false
    avoid_dynamic_calls: false
    directives_ordering: false
    sort_pub_dependencies: false